environment:
  name: prod
  project: cdf-bootcamp-13-prod # ex. cdf-bootcamp-01-prod
  type: prod # prod, staging, dev, test, qa
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-13-prod # ex. cdf-bootcamp-01-prod
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env

      # Groups
      # OBJECT ID FOR test/prod Groups
      data_developer_source_id: 9bc43b3c-7589-4438-be06-a83d77b769f7
      data_pipeline_oee_source_id: bf2541c2-155c-4773-b116-04c32fe5becd
      readwrite_source_id: 7bb8c596-ee45-41f2-9e24-e54eeeae45e4
      icapi_extractors_source_id: 29ae51ef-266c-4f06-823e-3db187798751

      # Client Ids (App registrations or Service Principals)
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env

      # Variables shared by modules
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      oee_space_name: oee_ts_space 
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee

      # Transformations
      schedule_hourly: "0 * * * *"
      pause_transformations: false
